### PR TITLE
Update to newest version of webpack

### PR DESCRIPTION
**Pull request by cyplo**
Updated all dependencies in the browser example project to avoid it
being affected by wasm loading issue - https://github.com/webpack/webpack/issues/8781

### CODE REVIEW

**Comment by cyplo** [comment]
Tested manually as I don't think we run the examples through CI - maybe we should - @zrzka ?

**Comment by cyplo** [comment]
@nazrhom @zrzka  - it's a problem with the component version - the same change passed CI for jellyschema [here](https://github.com/balena-io-modules/jellyschema/pull/116#event-2219609332)
Do I need to change something about this repo or is it a concourse/image issue ?

**Comment by zrzka** [comment]
@cyplo IMHO we can leave them out of CI. These're just examples how to use it. And to run them through CI, we have to change `package.json` to `file:../../target/npm/pkg`, because the version isn't published yet. Then the examples folder name will be kind of misleading, because you wont be able to run them out of CI if you don't modify `package.json` to point to some version, ... Probably not worth the hassle.

**Comment by cyplo** [comment]
I'm gonna remove `rust-toolchain` as see what's up

**Pull request merged**
