### PR TITLE
[WIP] Testing publish

### PR DESCRIPTION
**Pull request by nazrhom**
Change-type: patch
Signed-off-by: Giovanni Garufi <giovanni@balena.io>

### CODE REVIEW

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by zrzka** [comment]
@nazrhom does this `rust-public-crate` mean that we're going to test just Rust crate publishing and there's no WASM/NPM involved?

**Comment by nazrhom** [comment]
@zrzka no actually, it probably means I need some rest :P Fixed!

**Comment by zrzka** [comment]
@nazrhom can you also pls trash `.travis.yml` completely? As this will probably interfere with our publish as well and if Travis CI will be faster, our pipeline will fail (already published by Travis CI).

**Pull request merged**
